language: node_js
sudo: required  # See http://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
node_js:
  - "lts/*"
script: npm run test
branches:
  only:
    - master
cache:
  directories:
    - node_modules